CC = gcc
MAKESUB = $(MAKE) -C
BINDIR = ./bin
LIBDIR = ./lib
DEBUG_TARGET_LIB = $(LIBDIR)/libSLC.a
OBJDIR = ./o
DEBUG_OBJDIR = $(OBJDIR)/debug
RELEASE_OBJDIR = $(OBJDIR)/release
DEBUG_TARGET_TEST = $(BINDIR)/SLC_test.exe
DEBUG_OBJECTS_BASE = \
	$(DEBUG_OBJDIR)/SLC_Numbers.o \
	$(DEBUG_OBJDIR)/SLC_NumbersCopy.o \
	$(DEBUG_OBJDIR)/SLC_DLink.o
DEBUG_OBJECTS_CONTAINER = \
	$(DEBUG_OBJDIR)/SLC_Array.o \
	$(DEBUG_OBJDIR)/SLC_RingBuffer.o
DEBUG_OBJECTS_MATH = \
	$(DEBUG_OBJDIR)/SLC_Geometry.o \
	$(DEBUG_OBJDIR)/SLC_MiniBLAS.o \
	$(DEBUG_OBJDIR)/SLC_MiniLA.o \
	$(DEBUG_OBJDIR)/SLC_NLSLGN.o
DEBUG_OBJECTS_IO = \
	$(DEBUG_OBJDIR)/SLC_Log.o \
	$(DEBUG_OBJDIR)/SLC_PNG.o \
	$(DEBUG_OBJDIR)/SLC_pixmap.o
DEBUG_TESTOBJECTS_BASE = \
	$(DEBUG_OBJDIR)/SLC_NumbersUT.o \
	$(DEBUG_OBJDIR)/SLC_NumbersCopyUT.o \
	$(DEBUG_OBJDIR)/SLC_DLinkUT.o \
	$(DEBUG_OBJDIR)/SLC_TestUT.o
DEBUG_TEST_OBJECTS_CONTAINER = \
	$(DEBUG_OBJDIR)/SLC_ArrayUT.o \
	$(DEBUG_OBJDIR)/SLC_RingBufferUT.o
DEBUG_TEST_OBJECTS_MATH = \
	$(DEBUG_OBJDIR)/SLC_GeometryUT.o \
	$(DEBUG_OBJDIR)/SLC_MiniBLASUT.o \
	$(DEBUG_OBJDIR)/SLC_MiniLAUT.o \
	$(DEBUG_OBJDIR)/SLC_NLSLGNUT.o
DEBUG_TEST_OBJECTS_IO = \
	$(DEBUG_OBJDIR)/SLC_LogUT.o

.PHONY 	:	debug_test
debug_test	:	debug $(DEBUG_TARGET_TEST)
$(DEBUG_TARGET_TEST)	:	$(DEBUG_TARGET_LIB) $(DEBUG_TESTOBJECTS_BASE) $(DEBUG_TEST_OBJECTS_CONTAINER) \
							$(DEBUG_TEST_OBJECTS_MATH)
	mkdir -p $(BINDIR)
	$(CC) -o $@ $(DEBUG_TESTOBJECTS_BASE) $(DEBUG_TEST_OBJECTS_CONTAINER) $(DEBUG_TEST_OBJECTS_MATH) \
		-L$(LIBDIR) -lSLC -lpthread -lm

.PHONY	:	debug
debug	:	$(DEBUG_TARGET_LIB)
$(DEBUG_TARGET_LIB)	:	$(DEBUG_OBJECTS_BASE) $(DEBUG_OBJECTS_CONTAINER) $(DEBUG_OBJECTS_IO) $(DEBUG_OBJECTS_MATH)
	mkdir -p $(LIBDIR)
	$(AR) r $@ $^

$(DEBUG_OBJECTS_BASE)	:
	$(MAKESUB) 01Base debug

$(DEBUG_OBJECTS_CONTAINER)	:	$(DEBUG_OBJECTS_BASE)
	$(MAKESUB) 02Container debug

$(DEBUG_OBJECTS_IO)	:	$(DEBUG_OBJECTS_BASE)
	$(MAKESUB) 05IoDiag	debug

$(DEBUG_OBJECTS_MATH)	:	$(DEBUG_OBJECTS_BASE) $(DEBUG_OBJECTS_CONTAINER)
	$(MAKESUB) 03Math debug

$(DEBUG_TESTOBJECTS_BASE)	:	$(DEBUG_TARGET_LIB)
	$(MAKESUB) 01Base.UnitTest debug

$(DEBUG_TEST_OBJECTS_CONTAINER)	:	$(DEBUG_TARGET_LIB)
	$(MAKESUB) 02Container.UnitTest debug

$(DEBUG_TEST_OBJECTS_MATH)	:	$(DEBUG_TARGET_LIB)
	$(MAKESUB) 03Math.UnitTest debug

.PHONY	:	clean_debug
clean_debug	:
	rm -f $(DEBUG_TARGET_LIB)
	$(MAKESUB) 01Base clean_debug
	$(MAKESUB) 02Container clean_debug
	$(MAKESUB) 03Math clean_debug
	$(MAKESUB) 05IoDiag clean_debug
	$(MAKESUB) 01Base.UnitTest clean_debug
	$(MAKESUB) 02Container.UnitTest clean_debug
	$(MAKESUB) 03Math.UnitTest clean_debug