SLC_errno_t SLC_MiniBLASUT(SLC_i32_t settings)
{
    SLC_errno_t err = EXIT_SUCCESS;
    do {
        SLC_test(err, SLC_r32_MiniBLASUT, settings, __func__, __LINE__);
        SLC_test(err, SLC_r64_MiniBLASUT, settings, __func__, __LINE__);
        SLC_test(err, SLC_c64_MiniBLASUT, settings, __func__, __LINE__);
        SLC_test(err, SLC_c128_MiniBLASUT, settings, __func__, __LINE__);
    } while (0);
    SLC_testend(err, __func__, __LINE__);
    return err;
}